SkillsFundingAgency/das-providercommitments

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Authorisation/ProviderHandler.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Authorisation/ProviderRequirement.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Controllers/UnapprovedController.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Extensions/AuthorizationPolicyBuilderExtensions.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Startup.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Constants.cs

Adds an authorization filter for provider id

CV 81 add provider authorization policy

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/EditApprenticeshipViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Shared/_Layout.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Unapproved/Index.cshtml

PR created on behalf of FE dev.

Cv 98 add apprenticeship take 2

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Validators/AddDraftApprenticeshipViewModelValidatorTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Controllers/UnapprovedController.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/DependencyResolution/DefaultRegistry.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/AddDraftApprenticeshipViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Requests/AddDraftApprenticeshipViewModelValidator.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Startup.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Validators/AddDraftApprenticeshipRequestValidator.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Validators/AddDraftApprenticeshipViewModelValidator.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Validators/MonthYearValidator.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Shared/_ValidationSummary.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Unapproved/AddDraftApprenticeship.cshtml

Re-introduced date validation and validation messages on web page

Cv 127 frontend work

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.Commitments.Shared/SFA.DAS.Commitments.Shared.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.sln

This is a single empty package so we can get the build updated

Cv 185 create commitments common

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Extensions/NavigationBarSettingsExtensions.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/SFA.DAS.ProviderCommitments.Web.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Startup.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Features/ProviderFeature.cs

Pulls in lates UI package

---

azure/template.json

Replicated from https://github.com/SkillsFundingAgency/das-providercommitments/pull/86
- keys to be securestring
- renamed parameters
- create app service cert in arm template
- app service depends on cert deployment

Updated ARM template for migration of app services off ASE

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.IntegrationTests/SFA.DAS.ProviderCommitments.IntegrationTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.UnitTests/SFA.DAS.ProviderCommitments.UnitTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/SFA.DAS.ProviderCommitments.Web.UnitTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/SFA.DAS.ProviderCommitments.Web.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.csproj

Package update to use the packages generated from master instead of the dev branch.

CV-555 Package updated to Master

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/GetApprenticeshipsMapperTests/WhenGettingApprenticeships.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Models/Apprentice/IndexRequestTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/IndexRequest.cs

Also changed so that if you put less than 1 in the url it will force it back to page 1

MF-480 page 1 manage apprentices bug

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Customisations/ArrangeActionContextAttribute.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Filters/WhenAddingGoogleAnalyticsInformation.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Filters/GoogleAnalyticsFilter.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Startup.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Index.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Cohort/ConfirmEmployer.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/DraftApprenticeship/EditDraftApprenticeship.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Error/403.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Error/404.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Error/Error.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Shared/AddDraftApprenticeship.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Shared/SelectEmployer.cshtml

Revert of a revert failed after 2 attempts due to merge conflicts I wasn't able to solve, this is a new branch with the changes from the previous PR.
To be tested by Najam and I on 17/02/2020.

CV-543_AnalyticsProvider

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.IntegrationTests/SFA.DAS.ProviderCommitments.IntegrationTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.UnitTests/SFA.DAS.ProviderCommitments.UnitTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Extensions/DataLockStatusExtensionsTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/ApprenticeDetailsRequestToViewModelMapperTests/WhenIMapApprenticeDetailsRequestToViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/SFA.DAS.ProviderCommitments.Web.UnitTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Controllers/ApprenticeController.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/DependencyResolution/DefaultRegistry.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Extensions/DataLockStatusExtensions.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Apprentice/DetailsViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/DetailsViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/SFA.DAS.ProviderCommitments.Web.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Startup.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Details.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Inform.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.csproj

**Notes:**
- Compare to CV-587 when tech reviewing
- V2 Path: /{providerId}/apprentices/{apprenticeshipHashedId}
- Branch needs to be merged into master **after** CV-587
- Requires feature toggle: 
`
{
"Feature": "ChangeOfEmployer",
"IsEnabled": true,
"Whitelist": null
}
`

CV-586 Change employer link

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Extensions/DataLockStatusExtensionsTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/ApprenticeDetailsRequestToViewModelMapperTests/WhenIMapApprenticeDetailsRequestToViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Extensions/DataLockStatusExtensions.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Apprentice/DetailsViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/DetailsViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Startup.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Details.cshtml

Diff is against CV-583-backlink-to-search-page. On approval, it could be merged into this branch, or could supercede it, in which case it should target master.
Changes to triage options are in accordance with the following documentation:
https://skillsfundingagency.atlassian.net/wiki/spaces/NDL/pages/1700561095/Data+Lock+Triage+Options

Cv 583 data lock triage fixes

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/ApprenticesControllerTests/WhenPostingConfirm.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/IActionResultTestExtensions.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Controllers/ApprenticeController.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/RouteValues/RouteNames.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Confirm.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Sent.cshtml

Cv 594 submit change of employer request

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.IntegrationTests/SFA.DAS.ProviderCommitments.IntegrationTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.UnitTests/SFA.DAS.ProviderCommitments.UnitTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Apprentice/DetailsViewModelMapperTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/SFA.DAS.ProviderCommitments.Web.UnitTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Apprentice/DetailsViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/DetailsViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/SFA.DAS.ProviderCommitments.Web.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Details.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.csproj

Cv 682 completion date details

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Apprentice/DetailsViewModelMapperTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Apprentice/DetailsViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/DetailsViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Details.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Index.cshtml

CS-665 this change adds the email row to the apprentice details view page

Cs 665 add email address to details view

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.UnitTests/Commands/CreateCohort/WhenCreateCohortRequestIsHandled.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/CohortControllerTests/WhenGettingACohortWithDraftApprentice.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/CohortControllerTests/WhenGettingCohorts.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/CohortControllerTests/WhenGettingConfirmEmployer.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/CohortControllerTests/WhenGettingDeleteCohort.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/CohortControllerTests/WhenGettingDetails.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/CohortControllerTests/WhenGettingSelectEmployer.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/CohortControllerTests/WhenIPostConfirmEmployer.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/CohortControllerTests/WhenIPostDeleteCohortViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/CohortControllerTests/WhenIPostDraftApprenticeshipViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/CohortControllerTests/WhenPostingDetails.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Controllers/CohortController.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Application/Commands/CreateCohort/CreateCohortHandler.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Application/Commands/CreateCohort/CreateCohortResponse.cs

Correct issue with apprentice first before cohort creation for non levy provider journey

SV-566 Non levy reservation flow

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.IntegrationTests/SFA.DAS.ProviderCommitments.IntegrationTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.UnitTests/SFA.DAS.ProviderCommitments.UnitTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Apprentice/ConfirmRequestMapperTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Cohort/DetailsViewModelMapperTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/SFA.DAS.ProviderCommitments.Web.UnitTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Cohort/DetailsViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Cohort/CohortDraftApprenticeshipViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Cohort/DetailsViewCourseGroupingModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Cohort/DetailsViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Cohort/EmailOverlapsModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/SFA.DAS.ProviderCommitments.Web.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Cohort/Details.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.csproj

Cmad approvals changes provider merge 865 & 1030

Cmad approvals changes provider

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.IntegrationTests/SFA.DAS.ProviderCommitments.IntegrationTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Apprentice/WhenGettingApprenticeships.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Models/ApprenticeFilterModelTests/WhenGettingRouteData.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/SFA.DAS.ProviderCommitments.Web.UnitTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Apprentice/IndexViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/ApprenticesFilterModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/IndexRequest.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/SFA.DAS.ProviderCommitments.Web.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Index.cshtml

CS-1009-ApprenticeConfirmationFilter initial checkin

CS-1009-ApprenticeConfirmationFilter initial checkin

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.IntegrationTests/SFA.DAS.ProviderCommitments.IntegrationTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.UnitTests/SFA.DAS.ProviderCommitments.UnitTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/ApprenticesControllerTests/WhenCallingResendEmailInvitationTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/SFA.DAS.ProviderCommitments.Web.UnitTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Controllers/ApprenticeController.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Extensions/ITempDataDictionaryExtensions.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Apprentice/DetailsViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/DetailsViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/ResendEmailInvitationRequest.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/SFA.DAS.ProviderCommitments.Web.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Details.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Shared/_FlashMessagePartial.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/appsettings.Development.json

CS-1355-ResendInvitation-Provider

CS-1355-ResendInvitation-Provider

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Apprentice/ViewApprenticeshipUpdatesRequestToViewModelMapperTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Apprentice/ViewApprenticeshipUpdatesRequestToViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/ApprenticeshipUpdatesPartials/_ViewApprenticeshipUpdates.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/ApprenticeshipUpdatesPartials/_ViewOriginalApprenticeshipForApprenticeshipUpdates.cshtml

Pa 128 add delivery model to view changes page

Pa 128 add delivery model to view changes page

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Cohort/WhenIMapCreateCohortWithDraftApprenticeshipRequestToAddDraftApprenticeshipViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Cohort/AddDraftApprenticeshipViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/DraftApprenticeshipViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/RouteValues/RouteNames.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Shared/AddDraftApprenticeshipDetails.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Shared/DraftApprenticeship2.cshtml

Pa 199 show selected course on add draft page

Pa 199 show selected course on add draft page

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Apprentice/DetailsViewModelMapperTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Apprentice/DetailsViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/DetailsViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Details.cshtml

Pa 245 add emp price end date to approved view apprentice page

Pa 245 add emp price end date to approved view apprentice page

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/EditApprenticeship.cshtml

FJA-85 output hr where necessary

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Cohort/DetailsViewModelMapperTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/DraftApprenticeship/SelectDeliveryModelForEditViewModelMapperTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/DraftApprenticeshipTests/WhenIMapEditDraftApprenticeshipDetailsToViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Services/TempDataStorageService.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Controllers/DraftApprenticeshipController.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Extensions/ITempDataDictionaryExtensions.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Cohort/DetailsViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/DraftApprenticeship/SelectDeliveryModelForEditViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/EditDraftApprenticeshipViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/SelectDeliveryModelForEditViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Services/TempDataStorageService.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Startup.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/DraftApprenticeship/EditDraftApprenticeship.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/DraftApprenticeship/SelectDeliveryModelForEdit.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Infrastructure/OuterApi/Requests/DraftApprenticeship/GetEditDraftApprenticeshipSelectDeliveryModelRequest.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Infrastructure/OuterApi/Requests/DraftApprenticeships/GetEditDraftApprenticeshipRequest.cs

Fixes issue where CourseCode was not included in outer api call for Edit and Select DM pages

Adds TempDataStorageService and wires it into some mappers

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/DraftApprenticeshipTests/WhenIMapEditDraftApprenticeshipDetailsToViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/EditDraftApprenticeshipToUpdateRequestMapperTests/WhenIMapDraftApprenticeshipToUpdateRequest.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Controllers/DraftApprenticeshipController.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/EditDraftApprenticeshipToUpdateRequestMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/EditDraftApprenticeshipViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/ViewSelectOptionsViewModelToUpdateRequestMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/ViewDraftApprenticeshipViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Infrastructure/OuterApi/Requests/DraftApprenticeships/GetEditDraftApprenticeshipRequest.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.csproj

FLP-42 Training Provider: Edit the Pilot status for an apprentice - Pre-approval

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Apprentice/WhenGettingApprenticeships.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Apprentice/WhenGettingApprenticeshipsCsvContent.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Models/ApprenticeFilterModelTests/WhenGettingRouteData.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Extensions/SearchTermExtension.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Apprentice/DownloadApprenticesRequestMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Apprentice/IndexViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/ApprenticesFilterModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/DownloadRequest.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/IndexRequest.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Index.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.csproj

Pa 456 delivery model filter

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Apprentice/WhenGettingApprenticeships.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Apprentice/WhenGettingApprenticeshipsCsvContent.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Models/ApprenticeFilterModelTests/WhenGettingRouteData.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Extensions/SearchTermExtension.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Apprentice/DownloadApprenticesRequestMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Apprentice/IndexViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/ApprenticesFilterModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/DownloadRequest.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/IndexRequest.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Index.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.csproj

PA-510-IncludeConfirmationFilter

Pa 510 include confirmation filter

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Details.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Shared/DraftApprenticeship.cshtml

These changes are already reviewed and approved as part of feature branches

Base branch flp 90 101 116

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Shared/DraftApprenticeship.cshtml

FLP-119 Navigate to the [Add/Edit] training details page from the [Add/Edit] personal details page when the keyboard ‘Enter’ button is used

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Details.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/DetailsPartials/_DataLockBanner.cshtml

Updated content related to the data lock banner presented to pilot providers / for pilot apprenticeships

Flp 196 content data lock banner

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Authorization/AuthorizationContextProviderTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/SFA.DAS.ProviderCommitments.Web.UnitTests.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Authentication/AuthenticationExtensions.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Authentication/AuthenticationService.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Authentication/CustomServiceRole.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Authorization/AuthorizationContextProvider.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Controllers/ProviderAccountController.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Extensions/ServiceCollectionExtensions.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/SFA.DAS.ProviderCommitments.Web.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Configuration/ProviderCommitmentsConfigurationKeys.cs

Commit Details:
Integration of DfESignIn OpenIdConnect with the Provider Commitments service
1. Extending ServiceExtension to add DfESignIn Configuration.
2. Nuget Package upgrade required to adapt the above changes.

FAI-889 Provider Commitments DfESignIn Integration

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Cohort/CohortDraftApprenticeshipViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Cohort/Details.cshtml

Also fixed formatting of cost values in UI

Ensure columns in details table are not misaligned

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Mappers/Apprentice/DetailsViewModelMapperTests.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Mappers/Apprentice/DetailsViewModelMapper.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/DetailsViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Details.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/DetailsPartials/_ApprenticeshipStatus.cshtml

Ensure payment status is conditional on apprenticeship start and improve tag colours

Ensure payment status is conditional

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/Controllers/ErrorControllerTests/ErrorControllerTest.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web.UnitTests/WhenAddingServicesToTheContainer.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Authentication/AuthenticationExtensions.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Controllers/ErrorController.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Controllers/ProviderAccountController.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Extensions/ConfigurationExtensions.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Error/Error403ViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/SFA.DAS.ProviderCommitments.Web.csproj
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/ServiceRegistrations/ConfigurationServiceRegistrations.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/ServiceRegistrations/MvcServiceRegistrations.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Error/403.cshtml
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Configuration/AuthenticationSettings.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Configuration/IAuthenticationSettings.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments/Configuration/ProviderCommitmentsConfigurationKeys.cs

https://skillsfundingagency.atlassian.net/browse/FAI-2076

FAI-2076 Remove IDAMS Configurations

---

src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Models/Apprentice/DetailsViewModel.cs
src/SFA.DAS.ProviderCommitments/SFA.DAS.ProviderCommitments.Web/Views/Apprentice/Details.cshtml

FLP-1026 Automatically prevent change requests following a withdrawal
